#!/bin/bash

#######verificare licenta de cPanel in functie de failed###########

verlicenta=$(/usr/local/cpanel/cpkeyclt | grep -oh Failed)

##########de verificat mai jos in caz de openvz nou sa nu creeze reteaua pe altceva###############
###de adaugat sanity check pe pentru venet0:1#############


mainip=$(ifconfig venet0:1 | awk '$1 == "inet" {print $2}')
if [ "$verlicenta" = "Failed" ]
then
    	echo "Serverul nu are licenta sau IP-ul $mainip a fost deja folosit!"
        sleep 2

else
    	echo "Severul cu IP: $mainp are licenta activa!"
        sleep 2
        exit
fi
